export const part = [
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2F1615366963666.png&w=128&q=75",
    title:"Kontakt Home",
    faiz:"2,3,6,12,18 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"(012) 310 24 24",
    sayt:"www.kontakt.az",
    teyinat:"Texnika",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"1",
},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2F1651398282620.jpeg&w=128&q=75",
    title:"Irşad",
    faiz:"2,3,6,12,18 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"*0171",
    sayt:"www.irshad.az",
    teyinat:"Mobil telefon, Texnika",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"2",


    
},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2Foptimal_1548402916.jpg&w=128&q=75",
    title:"Optimal Electronics",
    faiz:"2,3,6,12,18 ay faizsiz",
    kesbek:"2% Cashback",
    mil:"1AZN=1.33Mil",
    tel:"(012) 954",
    sayt:"www.optimal.az",
    teyinat:"Texnika",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"3",

    
},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2Fbaku_electronics_1527859851.jpg&w=128&q=75",
    title:"Baku Electronics",
    faiz:"2,3,6,12,18 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"143",
    sayt:"www.bakuelectronics.az",
    teyinat:"Kompüter, Mobil telefon, Texnika",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"4",

    
},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2F1651515752075.jpeg&w=128&q=75",
    title:"Adore",
    faiz:"6 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"970",
    sayt:"www.adoregroup.az",
    teyinat:"Parfümeriya və Kosmetika",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"5",


    
},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2F1651832544732.jpeg&w=128&q=75",
    title:"Sabina",
    faiz:"6 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"",
    sayt:"",
    teyinat:"Parfümeriya və Kosmetika",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"6",


    
},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2F1651516186120.png&w=128&q=75",
    title:"MAC",
    faiz:"6 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"",
    sayt:"",
    teyinat:"Parfümeriya və Kosmetika",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"7",


    
},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2F1652190880054.png&w=128&q=75",
    title:"NYX PM",
    faiz:"6 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"",
    sayt:"",
    teyinat:"Parfümeriya və Kosmetika",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"8",


    
},
{
    img:"https://birbank.az/_next/image?url=%2Fimages%2Fpng%2FcategoryImages%2Ftshirt.png&w=96&q=75",
    title:"Dimarie",
    faiz:"3,6 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"(012) 510 25 06",
    sayt:"",
    teyinat:"Geyim",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"9",


    
},
{
    img:"https://birbank.az/_next/image?url=%2Fimages%2Fpng%2FcategoryImages%2Fstethoscope.png&w=96&q=75",
    title:"Təbriz Mehr Klnikası",
    faiz:"3,6 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"(012) 449 40 40",
    sayt:"",
    teyinat:"Tibb",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"10",


    
},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2Fworld_telecom_1536926119.jpg&w=128&q=75",
    title:"World Telecom",
    faiz:"2,3,6,12,18 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"*2555",
    sayt:"www.w-t.az",
    teyinat:"Mobil telefon, Texnika",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"11",


    
},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2Fbestel_1527598437.jpg&w=128&q=75",
    title:"Bestel",
    faiz:"3,6,12 ay faizsiz",
    kesbek:"3% Cashback",
    mil:"1AZN=2.00Mil",
    tel:"(012) 493 01 79",
    sayt:"www.bestel.az",
    teyinat:"Texnika",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"12",


    
},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2Feuromoda_1527768052.jpg&w=128&q=75",
    title:"Euromoda",
    faiz:"2,3,6 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"(012) 493-15-80",
    sayt:"-",
    teyinat:"Geyim",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"13",


    
},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2Framsey_1527850283.jpg&w=128&q=75",
    title:"Ramsey",
    faiz:"2,3,6 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"(012) 493 76 24",
    sayt:"-",
    teyinat:"Geyim",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"14",


    
},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2Ffaik_sonmez_1527767854.jpg&w=128&q=75",
    title:"Faik Sönmez",
    faiz:"2,3,6 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"055 209 38 08",
    sayt:"www.faiksonmez.com",
    teyinat:"Geyim",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"15",


    
},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2Fgallery_a_kids_1528194516.jpg&w=128&q=75",
    title:"Gallery4Kids",
    faiz:"2,3,6 ay faizsiz",
    kesbek:"5% Cashback",
    mil:"1AZN=3.33Mil",
    tel:"(012) 440 99 05",
    sayt:"www.gallery4kids.az/",
    teyinat:"Uşaqlar üçün",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"16",

},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2Falbano_1528440290.jpg&w=128&q=75",
    title:"Albano Moda",
    faiz:"3,6 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"(012) 492 19 53",
    sayt:"-",
    teyinat:"Geyim",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"17",
},
{
    img:"https://birbank.az/_next/image?url=%2Fimages%2Fpng%2FcategoryImages%2Ftshirt.png&w=96&q=75",
    title:"V style",
    faiz:"3,6 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"(012) 510 78 70",
    sayt:"-",
    teyinat:"Geyim",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"18",
},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2Funited_colors_of_benniton_1527853132.jpg&w=128&q=75",
    title:"United Colors of Benetton",
    faiz:"2,3,6 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"(012) 598 71 43",
    sayt:"www.benetton.com",
    teyinat:"Geyim",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"19",
},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2Faccessorize_1599633268.jpg&w=128&q=75",
    title:"Accessorize",
    faiz:"2,3,6 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"(012) 598 71 44",
    sayt:"-",
    teyinat:"Saat və aksesuarlar",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"20",
},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2Fbebe_1527767747.jpg&w=128&q=75",
    title:"Bebe",
    faiz:"2,3,6 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"(012) 598 71 50",
    sayt:"-",
    teyinat:"Geyim",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"21",
},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2Fcoccinelle_logo_1564467294.png&w=128&q=75",
    title:"Coccinelle",
    faiz:"2,3,6 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"(012) 598 71 65",
    sayt:"www.coccinelle.com",
    teyinat:"Geyim",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"22",
},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2Fhacket_london_1527769455.jpg&w=128&q=75",
    title:"Hackett London",
    faiz:"2,3,6 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"(012) 4974675",
    sayt:"-",
    teyinat:"Geyim",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"23",
},
{
    img:"https://birbank.az/_next/image?url=https%3A%2F%2Fbirbank.az%2Fapi%2Fpartner%2Fimage%2Fmonnalisa_1527853656.jpg&w=128&q=75",
    title:"Monnalisa",
    faiz:"2,3,6 ay faizsiz",
    kesbek:"",
    mil:"",
    tel:"(012) 598 19 87",
    sayt:"-",
    teyinat:"Geyim",
    sert:"*Taksit və Cashback şərtləri məhsul və kampaniyalar üzrə dəyişə bilər",
    sert2:"**Yalnız Kapital Bank pos-terminallarında",
    fb:"",
    ins:"",
    twit:"",
    id:"24",
},


]